name:                fints2ledger
version:             1.1.0
github:              "MoritzR/fints2ledger"
license:             MIT
author:              "Moritz Rumpf"
maintainer:          "moritz.rumpf@gmail.com"
copyright:           "2023 Moritz Rumpf"

extra-source-files:
- README.md
- CHANGELOG.md

data-files:
- data/*

# Metadata used when publishing your package
synopsis:            Download transactions from FinTS into a ledger journal 
category:            Finance, Console

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MoritzR/fints2ledger#readme>

dependencies:
- base >= 4.16.4 && < 4.16.5
- typed-process >= 0.2.11 && < 0.2.12  # for calling to python
- directory >= 1.3.6 && < 1.3.7 # for getting the users home directory
- filepath >= 1.4.2 && < 1.4.3 # for concatenating file paths
- yaml >= 0.11.11 && < 0.11.12 # for parsing yaml
- aeson >= 2.0.3 && < 2.0.4 # for json/yml parsing
- bytestring >= 0.11.4 && < 0.11.5 # for the ByteString Type, used by Aeson
- text >= 1.2.5 && < 1.2.6 # used by libraries instead of String
- haskeline >= 0.8.2 && < 0.8.3 # for autocompleting inputs
- hledger-lib >= 1.27.1 && < 1.27.2 # for autocompleting ledger accounts
- containers >= 0.6.5 && < 0.6.6 # for Maps and Sets
- text-format-heavy == 0.1.5.3 # for python like formatting of template strings
- cryptohash-md5 >= 0.11.101 && < 0.11.102 # for md5
- base16-bytestring >= 1.0.2 && < 1.0.3 # for md5 to hex
- regex-tdfa >= 1.3.2 && < 1.3.3 # for regex matching
- time >= 1.11.1 && < 1.11.2 # time library
- dates >= 0.2.3.2 && < 0.2.4 # for more flexible date parsing, like "30 days ago"
- optparse-applicative >= 0.17.0 && < 0.17.1 # for parsing CLI arguments
- transformers >= 0.5.6 && < 0.5.7 # For ReaderT
- brick == 1.4 # terminal UI library
- vty == 5.37 # underlying library for brick
- lens == 5.1.1 # lenses to use with brick
- generic-lens >= 2.2.2 && < 2.2.3 # automatically generate lenses
- cassava >= 0.5.3 && < 0.5.4 # csv encoding/decoding
- vector >= 0.12.3 && < 0.12.4 # list-like type, used by cassava

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-do-bind

default-extensions:
- DuplicateRecordFields
- OverloadedRecordDot
- OverloadedStrings
- NoFieldSelectors
- BlockArguments

library:
  source-dirs: src

executables:
  fints2ledger:
    main: Main.hs
    when:
    - condition: (flag(bundle_data_dir))
      then:
        source-dirs: app/bundled
      else:
        source-dirs: app/default
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fints2ledger

tests:
  fints2ledger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fints2ledger
    - sydtest # testing library
    - sydtest-discover # automatic test discovery
    - QuickCheck # property based testing library

flags:
  bundle_data_dir:
    description: Set the data dir to be relative to the executable for easier bundling
    default: false
    manual: true