name: binaries-linux

on:
  push:
    branches: [ hs ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Cache ghcup-installed tools
      id:   ghcup
      uses: actions/cache@v3
      with:
        path: ~/.ghcup
        key: ${{ runner.os }}-ghcup-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-ghcup

    - name: Cache cabal-installed libs
      id:   cabal
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-cabal-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-cabal

    - name: Install ghc
      run: |
        ghcup install ghc --set 9.2.7

    - name: Install dependencies
      run: |
          ghc --version
          cabal --version
          cabal update
          cabal build --dependencies-only

    - name: Build and install artifact
      run: |
          export ARTIFACTS=linux/fints2ledger
          mkdir -p ${ARTIFACTS}
          cp dist-newstyle/build/x86_64-linux/ghc-*/fints2ledger-*/x/fints2ledger/build/fints2ledger/fints2ledger ${ARTIFACTS}
          strip "${ARTIFACTS}/fints2ledger"

    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: linux
