name: binaries-linux

on:
  push:
    branches: [ hs ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        ghc-version: '9.2.7'

    - name: Install dependencies
      run: |
          cabal update
          cabal build --dependencies-only

    - name: Build and install artifact
      run: |
          export ARTIFACTS=linux-x64/fints2ledger
          mkdir -p ${ARTIFACTS}
          cabal install --installdir="${ARTIFACTS}" --install-method=copy --enable-executable-static -fbundle_data_dir 
          strip "${ARTIFACTS}/fints2ledger"
          cp -r data "${ARTIFACTS}"

    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: linux-x64

  macos:
    runs-on: macos-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        ghc-version: '9.2.7'

    - name: Install dependencies
      run: |
          cabal update
          cabal build --dependencies-only

    - name: Build and install artifact
      run: |
          export ARTIFACTS=mac-x64/fints2ledger
          mkdir -p ${ARTIFACTS}
          cabal install --installdir="${ARTIFACTS}" --install-method=copy --enable-executable-static -fbundle_data_dir 
          strip "${ARTIFACTS}/fints2ledger"
          cp -r data "${ARTIFACTS}"

    - uses: actions/upload-artifact@v3
      with:
        name: mac-x64
        path: mac-x64
