name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [master]
  # schedule:
  #   # additionally run once per week (At 00:00 on Sunday) to maintain cache
  #   - cron: '0 0 * * 0'

jobs:
  build:
    name: ${{ matrix.os }} / build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.7'

    - name: Install dependencies
      run: |
        cabal build --only-dependencies

    - name: Build
      run: |
        cabal build

    - name: Test
      run: |
        cabal test
